---
language: node_js
node_js:
  - 5

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin


script:
  - set -e
  - npm run test
  - npm run build
  - git rev-parse HEAD > dist/fingerprint.txt


after_success:
  - aws s3 sync dist/ s3://bazile.tinytracker/ --delete
